
all: Pipfile.lock requirements.txt

Pipfile.lock: Pipfile
	pipenv lock

requirements.txt: Pipfile
	echo "# This file is automatically generated with make" > requirements.txt
	echo "# Any changes will be overwritten!" >> requirements.txt
	pipenv lock -r >> requirements.txt
